# Generated by Django 4.1.1 on 2022-09-23 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
