# Generated by Django 4.1.1 on 2022-09-25 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bid_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bid_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_listings', to='auctions.listing')),
                ('bidder', models.ManyToManyField(blank=True, related_name='bidders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
