# Generated by Django 4.1.1 on 2022-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
